name: KitKB
main: kitkb\KitKb
version: 1.1.0
api: "2.0.0"
author: jkorn
description: "A kit plugin with custom knockback."
website: "https://github.com/jkorn2324"

permissions:
  permission.kit:
    description: "Allows players to create/delete kits."
    default: op
  permission.kit.list:
    default: true
    description: "Allows players to view the list of the kits."
  permission.kit.kb:
    default: op
    description: "Allows players to edit the knockback of the kits while in game.";
  permission.kit.kbinfo:
    default: op
    description: "Allows players to view the knockback information of a kit."